#! /usr/bin/python3

import base59
import nacl.pwhash
import nacl.secret
import nacl.utils
import sys

def main():
    if len(sys.argv) != 2:
        print("Usage: client msg")
        sys.exit(1)

    msg = sys.argv[1]

    send_key = nacl.utils.random(16)
    encryption_key = nacl.pwhash.argon2i.kdf(nacl.secret.SecretBox.KEY_SIZE,
                                             send_key,
                                             b'0123456789abcdef',
                                             opslimit=nacl.pwhash.argon2i.OPSLIMIT_SENSITIVE,
                                             memlimit=nacl.pwhash.argon2i.MEMLIMIT_SENSITIVE)

    print(type(send_key))
    print(base58.b58encode(send_key))
    print(type(encryption_key))
    print(base58.b58encode(encryption_key))

    box = nacl.secret.SecretBox(encryption_key)
    encrypted = box.encrypt(msg.encode('utf-8'))

    print(encrypted)

if __name__ == "__main__":
    main()
